from ahmaths import create_app, db
from ahmaths.models import Topic, Subtopic, Question, Paper, User

app = create_app()


def setup_db(db, app):

    with app.app_context():
        db.create_all()

        db.session.add(User(email='neelu.rsa@gmail.com', password='$2b$12$Q9OiQeBop4waQDri5.YwMeOus2yzYKmTJ.es0zT5707aQBG.T5mDS'))

        db.session.add(Topic(topic_id='partial_fractions', topic_name='Partial Fractions'))
        db.session.add(Topic(topic_id='binomial_theorem', topic_name='Binomial Theorem'))
        db.session.add(Topic(topic_id='differentiation', topic_name='Differentiation'))
        db.session.add(Topic(topic_id='integration', topic_name='Integration'))
        db.session.add(Topic(topic_id='differential_equations', topic_name='Differential Equations'))
        db.session.add(Topic(topic_id='functions_graphs', topic_name='Functions &amp; Graphs'))
        db.session.add(Topic(topic_id='systems_of_equations', topic_name='Systems of Equations'))
        db.session.add(Topic(topic_id='complex_numbers', topic_name='Complex Numbers'))
        db.session.add(Topic(topic_id='sequences_series', topic_name='Sequences &amp; Series'))
        db.session.add(Topic(topic_id='maclaurin_series', topic_name='Maclaurin Series'))
        db.session.add(Topic(topic_id='matrices', topic_name='Matrices'))
        db.session.add(Topic(topic_id='vectors', topic_name='Vectors'))
        db.session.add(Topic(topic_id='methods_of_proof', topic_name='Methods of Proof'))
        db.session.add(Topic(topic_id='number_theory', topic_name='Number Theory'))

        db.session.add(Subtopic(subtopic_id='new_functions', subtopic_name='New Functions and their Derivatives', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='chain_rule', subtopic_name='Chain Rule', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='product_rule', subtopic_name='Product Rule', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='quotient_rule', subtopic_name='Quotient Rule', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='second_derivative', subtopic_name='Second Derivative', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='parametric', subtopic_name='Parametric Differentiation', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='implicit', subtopic_name='Implicit Differentiation', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='logarithmic', subtopic_name='Logarithmic Differentiation', topic_id='differentiation'))
        db.session.add(Subtopic(subtopic_id='related_rates', subtopic_name='Related Rates of Change', topic_id='differentiation'))

        db.session.add(Subtopic(subtopic_id='euclidean_algorithm', subtopic_name='Euclidean Algorithm', topic_id='number_theory'))
        db.session.add(Subtopic(subtopic_id='number_theory', subtopic_name='Number Bases', topic_id='number_theory'))

        db.session.add(Subtopic(subtopic_id='distinct_linear_factors', subtopic_name='Partial Fractions with Distinct Linear Factors', topic_id='partial_fractions'))
        db.session.add(Subtopic(subtopic_id='repeated_linear_factor', subtopic_name='Partial Fractions with a Repeated Linear Factors', topic_id='partial_fractions'))
        db.session.add(Subtopic(subtopic_id='irreducible_quadratic_factor', subtopic_name='Partial Fractions with an Irreducible Quadratic Factor', topic_id='partial_fractions'))
        db.session.add(Subtopic(subtopic_id='improper_rational_fraction', subtopic_name='Partial Fractions of an Improper Rational Fraction', topic_id='partial_fractions'))

        db.session.add(Subtopic(subtopic_id='standard_integrals', subtopic_name='Standard Integrals and Useful Forms', topic_id='integration'))
        db.session.add(Subtopic(subtopic_id='integration_partial_fractions', subtopic_name='Integration by Partial Fractions', topic_id='integration'))
        db.session.add(Subtopic(subtopic_id='substitution', subtopic_name='Integration by Substitution', topic_id='integration'))
        db.session.add(Subtopic(subtopic_id='parts', subtopic_name='Integration by Parts', topic_id='integration'))
        db.session.add(Subtopic(subtopic_id='volumes_of_revolution', subtopic_name='Volumes of Revolution', topic_id='integration'))

        db.session.add(Subtopic(subtopic_id='binomial_expansion', subtopic_name='Binomial Expansions', topic_id='binomial_theorem'))
        db.session.add(Subtopic(subtopic_id='general_term', subtopic_name='Finding and Using the General Term', topic_id='binomial_theorem'))

        db.session.add(Subtopic(subtopic_id='gaussian_elimination', subtopic_name='Gaussian Elimination', topic_id='systems_of_equations'))
        db.session.add(Subtopic(subtopic_id='inconsistency_redundancy', subtopic_name='Inconsistency and Redundancy', topic_id='systems_of_equations'))
        db.session.add(Subtopic(subtopic_id='ill_conditioning', subtopic_name='Ill-Conditioning', topic_id='systems_of_equations'))

        db.session.add(Subtopic(subtopic_id='direct', subtopic_name='Direct Proof', topic_id='methods_of_proof'))
        db.session.add(Subtopic(subtopic_id='contrapositive', subtopic_name='Proof by Contrapositive', topic_id='methods_of_proof'))
        db.session.add(Subtopic(subtopic_id='contradiction', subtopic_name='Proof by Contradiction', topic_id='methods_of_proof'))
        db.session.add(Subtopic(subtopic_id='induction', subtopic_name='Proof by Induction', topic_id='methods_of_proof'))
        db.session.add(Subtopic(subtopic_id='counter_example', subtopic_name='Disproving by Counter-Example', topic_id='methods_of_proof'))

        db.session.add(Paper(paper_name='Specimen Paper (2000)', paper_id='Specimen(2000)'))
        db.session.add(Paper(paper_name='2002 Paper', paper_id='2002'))
        db.session.add(Paper(paper_name='2003 Paper', paper_id='2003'))
        db.session.add(Paper(paper_name='2004 Paper', paper_id='2004'))
        db.session.add(Paper(paper_name='Specimen Paper (2004)', paper_id='Specimen(2004)'))
        db.session.add(Paper(paper_name='2005 Paper', paper_id='2005'))
        db.session.add(Paper(paper_name='2006 Paper', paper_id='2006'))
        db.session.add(Paper(paper_name='2007 Paper', paper_id='2007'))
        db.session.add(Paper(paper_name='2008 Paper', paper_id='2008'))
        db.session.add(Paper(paper_name='2009 Paper', paper_id='2009'))
        db.session.add(Paper(paper_name='2010 Paper', paper_id='2010'))
        db.session.add(Paper(paper_name='2011 Paper', paper_id='2011'))
        db.session.add(Paper(paper_name='2012 Paper', paper_id='2012'))
        db.session.add(Paper(paper_name='2013 Paper', paper_id='2013'))
        db.session.add(Paper(paper_name='2014 Paper', paper_id='2014'))
        db.session.add(Paper(paper_name='2015 Paper', paper_id='2015'))
        db.session.add(Paper(paper_name='2016 Paper', paper_id='2016'))
        db.session.add(Paper(paper_name='Specimen Paper (2016)', paper_id='Specimen(2016)'))
        db.session.add(Paper(paper_name='2017 Paper', paper_id='2017'))
        db.session.add(Paper(paper_name='2018 Paper', paper_id='2018'))


        db.session.add(Question(marks=10, question_id='2007Q16', question_number='16', video='eOUZqLLSx6g?start=0', paper='2007', topics='functions_graphs'))
        db.session.add(Question(marks=10, question_id='2007Q15', question_number='15', video='TYhSuKxzquU?start=0', paper='2007', topics='vectors'))
        db.session.add(Question(marks=10, question_id='2007Q14', question_number='14', video='vpdzupLY2d8?start=0', paper='2007', topics='differential_equations'))
        db.session.add(Question(marks=10, question_id='2007Q13', question_number='13', video='PlIz6SBQCqY?start=0', paper='2007', topics='differentiation', subtopics='parametric,second_derivative'))
        db.session.add(Question(marks=5, question_id='2007Q12', question_number='12', video='s8EBOIIJGhY?start=0', paper='2007', topics='methods_of_proof', subtopics='induction'))
        db.session.add(Question(marks=4, question_id='2007Q11', question_number='11', video='d9cPOfO5WRs?start=0', paper='2007', topics='complex_numbers'))
        db.session.add(Question(marks=6, question_id='2007Q10', question_number='10', video='H4hYUGphb2E?start=0', paper='2007', topics='integration', subtopics='substitution,volumes_of_revolution'))
        db.session.add(Question(marks=5, question_id='2007Q9', question_number='9', video='6l3Q6w3mdA8?start=0', paper='2007', topics='sequences_series'))
        db.session.add(Question(marks=6, question_id='2007Q8', question_number='8', video='erxe49vXJhs?start=0', paper='2007', topics='differential_equations'))
        db.session.add(Question(marks=4, question_id='2007Q7', question_number='7', video='dvSu2_7m1CE?start=0', paper='2007', topics='number_theory', subtopics='euclidean_algorithm'))
        db.session.add(Question(marks=5, question_id='2007Q6', question_number='6', video='4hetaOAAoHs?start=0', paper='2007', topics='maclaurin_series'))
        db.session.add(Question(marks=5, question_id='2007Q5', question_number='5', video='lJa89WOjqJ4?start=0', paper='2007', topics='matrices'))
        db.session.add(Question(marks=6, question_id='2007Q4', question_number='4', video='dSubWteGbqQ?start=0', paper='2007', topics='integration,partial_fractions', subtopics='distinct_linear_factors,integration_partial_fractions'))
        db.session.add(Question(marks=4, question_id='2007Q3', question_number='3', video='7Ll3-vjsWNc?start=0', paper='2007', topics='complex_numbers'))
        db.session.add(Question(marks=6, question_id='2007Q2', question_number='2', video='mhJuZePRqxg?start=0', paper='2007', topics='differentiation', subtopics='chain_rule,logarithmic'))
        db.session.add(Question(marks=4, question_id='2007Q1', question_number='1', video='hj6WKFp47Yk?start=0', paper='2007', topics='binomial_theorem', subtopics='binomial_expansion'))

        db.session.add(Question(marks=10, question_id='2008Q16', question_number='16', video='mCiSzGAW4ws?start=0', paper='2008', topics='complex_numbers'))
        db.session.add(Question(marks=9, question_id='2008Q15', question_number='15', video='MZCIWyWxTxI?start=0', paper='2008', topics='differentiation,functions_graphs', subtopics='quotient_rule,second_derivative'))
        db.session.add(Question(marks=10, question_id='2008Q14', question_number='14', video='ZrY8blDY8Po?start=0', paper='2008', topics='vectors'))
        db.session.add(Question(marks=10, question_id='2008Q13', question_number='13', video='I9bwIW0xnYE?start=0', paper='2008', topics='differential_equations'))
        db.session.add(Question(marks=7, question_id='2008Q12', question_number='12', video='GFM6UgYMXpo?start=0', paper='2008', topics='maclaurin_series'))
        db.session.add(Question(marks=5, question_id='2008Q11', question_number='11', video='0rffGr4Lafc?start=0', paper='2008', topics='methods_of_proof', subtopics='direct,counter_example'))
        db.session.add(Question(marks=5, question_id='2008Q10', question_number='10', video='nyyLGBEwSgg?start=0', paper='2008', topics='integration,differentiation'))
        db.session.add(Question(marks=4, question_id='2008Q9', question_number='9', video='spXoywTyLgE?start=0', paper='2008', topics='integration'))
        db.session.add(Question(marks=5, question_id='2008Q8', question_number='8', video='LIjjWuNJ240?start=0', paper='2008', topics='binomial_theorem', subtopics='general_term'))
        db.session.add(Question(marks=5, question_id='2008Q7', question_number='7', video='ql1Bx0u0bk8?start=0', paper='2008', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=5, question_id='2008Q6', question_number='6', video='lUMQ7aIdc8M?start=0', paper='2008', topics='matrices'))
        db.session.add(Question(marks=6, question_id='2008Q5', question_number='5', video='N7PJ7LsMn0g?start=0', paper='2008', topics='differentiation', subtopics='implicit,product_rule'))
        db.session.add(Question(marks=6, question_id='2008Q4', question_number='4', video='eVghdQ_7vIc?start=0', paper='2008', topics='integration,partial_fractions', subtopics='irreducible_quadratic_factor,integration_partial_fractions'))
        db.session.add(Question(marks=4, question_id='2008Q3', question_number='3', video='V_yC3xqpCL8?start=0', paper='2008', topics='functions_graphs'))
        db.session.add(Question(marks=5, question_id='2008Q2', question_number='2', video='4C2XlmMJEqM?start=0', paper='2008', topics='differentiation', subtopics='chain_rule,parametric'))
        db.session.add(Question(marks=4, question_id='2008Q1', question_number='1', video='7VTc5Kg1tH0?start=0', paper='2008', topics='sequences_series'))

        db.session.add(Question(marks=11, question_id='2009Q16', question_number='16', video='oK4gHBzI3Ls?start=0', paper='2009', topics='vectors,systems_of_equations', subtopics='gaussian_elimination'))
        db.session.add(Question(marks=10, question_id='2009Q15', question_number='15', video='ZJq9fGLxwwQ?start=0', paper='2009', topics='differential_equations'))
        db.session.add(Question(marks=9, question_id='2009Q14', question_number='14', video='xTSqgnKEfqE?start=0', paper='2009', topics='maclaurin_series,partial_fractions', subtopics='repeated_linear_factor'))
        db.session.add(Question(marks=10, question_id='2009Q13', question_number='13', video='W_jMHn73TBA?start=0', paper='2009', topics='functions_graphs'))
        db.session.add(Question(marks=5, question_id='2009Q12', question_number='12', video='gmX9Tai9D3I?start=0', paper='2009', topics='sequences_series'))
        db.session.add(Question(marks=5, question_id='2009Q11', question_number='11', video='wM1hmUWBTSA?start=0', paper='2009', topics='differentiation', subtopics='logarithmic,product_rule'))
        db.session.add(Question(marks=4, question_id='2009Q10', question_number='10', video='ZJXEiEfGq7E?start=0', paper='2009', topics='number_theory', subtopics='euclidean_algorithm'))
        db.session.add(Question(marks=5, question_id='2009Q9', question_number='9', video='8BbsLdxPwlI?start=0', paper='2009', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=3, question_id='2009Q8', question_number='8', video='Ob_TxF_SbuU?start=0', paper='2009', topics='binomial_theorem', subtopics='binomial_expansion'))
        db.session.add(Question(marks=6, question_id='2009Q7', question_number='7', video='OzceC_eaY94?start=0', paper='2009', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=6, question_id='2009Q6', question_number='6', video='W8wwby9T-CQ?start=0', paper='2009', topics='complex_numbers'))
        db.session.add(Question(marks=4, question_id='2009Q5', question_number='5', video='zgUsQztgn8g?start=0', paper='2009', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=5, question_id='2009Q4', question_number='4', video='XMJQ5V5xErA?start=0', paper='2009', topics='methods_of_proof', subtopics='induction'))
        db.session.add(Question(marks=4, question_id='2009Q3', question_number='3', video='0Ryd6rPqt8A?start=0', paper='2009', topics='differential_equations'))
        db.session.add(Question(marks=5, question_id='2009Q2', question_number='2', video='evHsJ3Hfzxk?start=0', paper='2009', topics='matrices'))
        db.session.add(Question(marks=4, question_id='2009Q1b', question_number='1b', video='ISffSjeepj8?start=190', paper='2009', topics='differentiation', subtopics='implicit,product_rule,quotient_rule'))
        db.session.add(Question(marks=3, question_id='2009Q1a', question_number='1a', video='ISffSjeepj8?start=0', paper='2009', topics='differentiation', subtopics='product_rule'))

        db.session.add(Question(marks=10, question_id='2010Q16', question_number='16', video='muWDwtB6IF0?start=616', paper='2010', topics='complex_numbers'))
        db.session.add(Question(marks=10, question_id='2010Q15', question_number='15', video='muWDwtB6IF0?start=256', paper='2010', topics='integration', subtopics='volumes_of_revolution'))
        db.session.add(Question(marks=10, question_id='2010Q14', question_number='14', video='muWDwtB6IF0?start=8', paper='2010', topics='matrices'))
        db.session.add(Question(marks=10, question_id='2010Q13', question_number='13', video='7_6Z0RGzRtM?start=1325', paper='2010', topics='differentiation,functions_graphs', subtopics='parametric,second_derivative'))
        db.session.add(Question(marks=4, question_id='2010Q12', question_number='12', video='7_6Z0RGzRtM?start=1190', paper='2010', topics='methods_of_proof', subtopics='contradiction'))
        db.session.add(Question(marks=7, question_id='2010Q11', question_number='11', video='7_6Z0RGzRtM?start=970', paper='2010', topics='differential_equations'))
        db.session.add(Question(marks=3, question_id='2010Q10', question_number='10', video='7_6Z0RGzRtM?start=840', paper='2010', topics='functions_graphs'))
        db.session.add(Question(marks=4, question_id='2010Q9', question_number='9', video='7_6Z0RGzRtM?start=467', paper='2010', topics='maclaurin_series'))
        db.session.add(Question(marks=6, question_id='2010Q8', question_number='8', video='7_6Z0RGzRtM?start=215', paper='2010', topics='methods_of_proof', subtopics='direct,induction'))
        db.session.add(Question(marks=6, question_id='2010Q7', question_number='7', video='7_6Z0RGzRtM?start=10', paper='2010', topics='partial_fractions,integration', subtopics='distinct_linear_factors,integration_partial_fractions'))
        db.session.add(Question(marks=4, question_id='2010Q6', question_number='6', video='Lr1J2m2e1vQ?start=890', paper='2010', topics='vectors'))
        db.session.add(Question(marks=4, question_id='2010Q5', question_number='5', video='Lr1J2m2e1vQ?start=675', paper='2010', topics='binomial_theorem', subtopics='factorials_choose'))  # proof?
        db.session.add(Question(marks=4, question_id='2010Q4', question_number='4', video='Lr1J2m2e1vQ?start=405', paper='2010', topics='matrices'))
        db.session.add(Question(marks=7, question_id='2010Q3', question_number='3', video='Lr1J2m2e1vQ?start=285', paper='2010', topics='integration', subtopics='substitution,parts'))
        db.session.add(Question(marks=5, question_id='2010Q2', question_number='2', video='Lr1J2m2e1vQ?start=140', paper='2010', topics='sequences_series'))
        db.session.add(Question(marks=6, question_id='2010Q1', question_number='1', video='Lr1J2m2e1vQ?start=8', paper='2010', topics='differentiation', subtopics='chain_rule,product_rule,quotient'))

        db.session.add(Question(marks=11, question_id='2011Q16', question_number='16', video='zqqK1SCdzx0?start=765', paper='2011', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=10, question_id='2011Q15', question_number='15', video='zqqK1SCdzx0?start=418', paper='2011', topics='vectors'))
        db.session.add(Question(marks=10, question_id='2011Q14', question_number='14', video='zqqK1SCdzx0?start=7', paper='2011', topics='differential_equations'))
        db.session.add(Question(marks=9, question_id='2011Q13', question_number='13', video='RvdPRAU_Irg?start=1020', paper='2011', topics='sequences_series'))
        db.session.add(Question(marks=5, question_id='2011Q12', question_number='12', video='RvdPRAU_Irg?start=725', paper='2011', topics='methods_of_proof', subtopics='induction'))
        db.session.add(Question(marks=7, question_id='2011Q11', question_number='11', video='RvdPRAU_Irg?start=542', paper='2011', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=5, question_id='2011Q10', question_number='10', video='RvdPRAU_Irg?start=405', paper='2011', topics='complex_numbers'))
        db.session.add(Question(marks=5, question_id='2011Q9', question_number='9', video='RvdPRAU_Irg?start=298', paper='2011', topics='differential_equations'))
        db.session.add(Question(marks=4, question_id='2011Q8', question_number='8', video='RvdPRAU_Irg?start=175', paper='2011', topics='sequences_series'))
        db.session.add(Question(marks=4, question_id='2011Q7', question_number='7', video='RvdPRAU_Irg?start=7', paper='2011', topics='differentiation', subtopics='chain_rule,product_rule,quotient_rule'))
        db.session.add(Question(marks=4, question_id='2011Q6', question_number='6', video='avhupPO6XlY?start=1117', paper='2011', topics='functions_graphs'))
        db.session.add(Question(marks=6, question_id='2011Q5', question_number='5', video='avhupPO6XlY?start=750', paper='2011', topics='maclaurin_series'))
        db.session.add(Question(marks=6, question_id='2011Q4', question_number='4', video='avhupPO6XlY?start=526', paper='2011', topics='matrices'))
        db.session.add(Question(marks=3, question_id='2011Q3b', question_number='3b', video='avhupPO6XlY?start=441', paper='2011', topics='differentiation', subtopics='chain_rule,product_rule'))
        db.session.add(Question(marks=3, question_id='2011Q3a', question_number='3a', video='avhupPO6XlY?start=356', paper='2011', topics='differentiation', subtopics='chain_rule,implicit'))
        db.session.add(Question(marks=3, question_id='2011Q2', question_number='2', video='avhupPO6XlY?start=220', paper='2011', topics='binomial_theorem', subtopics='binomial_expansion'))
        db.session.add(Question(marks=5, question_id='2011Q1', question_number='1', video='avhupPO6XlY?start=8', paper='2011', topics='integration,partial_fractions', subtopics='distinct_linear_factors,integration_partial_fractions'))

        db.session.add(Question(marks=4, question_id='2012Q16b', question_number='16b', video='l2-da3M4umE?start=278', paper='2012', topics='complex_numbers'))
        db.session.add(Question(marks=6, question_id='2012Q16a', question_number='16a', video='l2-da3M4umE?start=0', paper='2012', topics='methods_of_proof,complex_numbers', subtopics='induction'))
        db.session.add(Question(marks=11, question_id='2012Q15', question_number='15', video='K-p3ZLQbfpc?start=0', paper='2012', topics='differential_equations,partial_fractions', subtopics='repeated_linear_factor'))
        db.session.add(Question(marks=9, question_id='2012Q14', question_number='14', video='MMZvOu9JU0Q?start=0', paper='2012', topics='systems_of_equations', subtopics='gaussian_elimination,inconsistency_redundancy,ill_conditioning'))
        db.session.add(Question(marks=10, question_id='2012Q13', question_number='13', video='s-WyHrtqQX0?start=0', paper='2012', topics='differentiation,functions_graphs', subtopics='parametric,second_derivative'))
        db.session.add(Question(marks=5, question_id='2012Q12', question_number='12', video='PVH_1-Ye_SA?start=0', paper='2012', topics='differentiation', subtopics='related_rates'))
        db.session.add(Question(marks=5, question_id='2012Q11', question_number='11', video='2veikl1yAPM?start=0', paper='2012', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=3, question_id='2012Q10', question_number='10', video='cX-mdzT3ylI?start=0', paper='2012', topics='number_theory', subtopics='number_bases'))
        db.session.add(Question(marks=4, question_id='2012Q9', question_number='9', video='CbYoYNxgWsA?start=0', paper='2012', topics='matrices'))
        db.session.add(Question(marks=6, question_id='2012Q8', question_number='8', video='_zo1JTiG4tA?start=0', paper='2012', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=4, question_id='2012Q7', question_number='7', video='vat834ndQtw?start=0', paper='2012', topics='functions_graphs'))
        db.session.add(Question(marks=5, question_id='2012Q6', question_number='6', video='UOl8vuFDRog?start=0', paper='2012', topics='maclaurin_series'))
        db.session.add(Question(marks=5, question_id='2012Q5', question_number='5', video='SpaaVJ639bo?start=0', paper='2012', topics='vectors'))
        db.session.add(Question(marks=5, question_id='2012Q4', question_number='4', video='y-YKHAjQ6qU?start=0', paper='2012', topics='binomial_theorem', subtopics='general_term'))
        db.session.add(Question(marks=6, question_id='2012Q3', question_number='3', video='K4PVBmKqLqI?start=0', paper='2012', topics='complex_numbers'))
        db.session.add(Question(marks=5, question_id='2012Q2', question_number='2', video='HF0FzGfiyHk?start=0', paper='2012', topics='sequences_series'))
        db.session.add(Question(marks=7, question_id='2012Q1', question_number='1', video='HiuC1qtuJEM?start=0', paper='2012', topics='differentiation', subtopics='chain_rule,product_rule,quotient_rule'))

        db.session.add(Question(marks=10, question_id='2013Q17', question_number='17', video='12KUGzzHUwE?start=0', paper='2013', topics='sequences_series'))
        db.session.add(Question(marks=10, question_id='2013Q16', question_number='16', video='hiQ5iYAV6AI?start=0', paper='2013', topics='differential_equations'))
        db.session.add(Question(marks=9, question_id='2013Q15', question_number='15', video='4l-XenQeuxE?start=0', paper='2013', topics='vectors'))
        db.session.add(Question(marks=11, question_id='2013Q14', question_number='14', video='KObm65cja9Y?start=0', paper='2013', topics='differential_equations'))
        db.session.add(Question(marks=5, question_id='2013Q13', question_number='13', video='zbZMU9k5p20?start=0', paper='2013', topics='functions_graphs'))
        db.session.add(Question(marks=4, question_id='2013Q12', question_number='12', video='coo93VluPPU?start=0', paper='2013', topics='methods_of_proof', subtopics='direct,counter_example'))
        db.session.add(Question(marks=6, question_id='2013Q11', question_number='11', video='575GpT2WkRE?start=0', paper='2013', topics='differentiation', subtopics='chain_rule,product_rule,implicit,second_derivative'))
        db.session.add(Question(marks=5, question_id='2013Q10', question_number='10', video='kP6C0X6u0dk?start=0', paper='2013', topics='complex_numbers'))
        db.session.add(Question(marks=6, question_id='2013Q9', question_number='9', video='x9hVV0yIdGs?start=0', paper='2013', topics='methods_of_proof', subtopics='induction'))
        db.session.add(Question(marks=5, question_id='2013Q8', question_number='8', video='mrJLEImGoUM?start=0', paper='2013', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=4, question_id='2013Q7', question_number='7', video='EU4JL7bZTvg?start=0', paper='2013', topics='complex_numbers'))
        db.session.add(Question(marks=4, question_id='2013Q6', question_number='6', video='vSph3QmgauM?start=0', paper='2013', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=4, question_id='2013Q5', question_number='5', video='XSYFEm-hKUU?start=0', paper='2013', topics='number_theory', subtopics='number_bases'))
        db.session.add(Question(marks=5, question_id='2013Q4', question_number='4', video='qrOfEzizL0k?start=0', paper='2013', topics='integration'))
        db.session.add(Question(marks=5, question_id='2013Q3', question_number='3', video='enYKB52-qos?start=0', paper='2013', topics='matrices'))
        db.session.add(Question(marks=3, question_id='2013Q2', question_number='2', video='Q6OWBXZbDUM?start=0', paper='2013', topics='differentiation', subtopics='chain_rule,product_rule'))
        db.session.add(Question(marks=4, question_id='2013Q1', question_number='1', video='bhsFoJSYkEg?start=0', paper='2013', topics='binomial_theorem', subtopics='binomial_expansion'))

        db.session.add(Question(marks=10, question_id='2014Q16', question_number='16', video='25Wnxd5-rGA?start=0', paper='2014', topics='complex_numbers'))
        db.session.add(Question(marks=10, question_id='2014Q15', question_number='15', video='3Znfz26rrbk?start=0', paper='2014', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=10, question_id='2014Q14', question_number='14', video='F7lHPwYTyX8?start=0', paper='2014', topics='sequences_series,partial_fractions', subtopics='distinct_linear_factors'))
        db.session.add(Question(marks=10, question_id='2014Q13', question_number='13', video='Rp7WSiDRQmY?start=0', paper='2014', topics='differentiation,functions_graphs', subtopics='product_rule'))
        db.session.add(Question(marks=6, question_id='2014Q12', question_number='12', video='KqpBMhc-jrI?start=0', paper='2014', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=6, question_id='2014Q11', question_number='11', video='BP6O0kOnUfs?start=0', paper='2014', topics='functions_graphs'))
        db.session.add(Question(marks=5, question_id='2014Q10', question_number='10', video='MRVmUJI8qTQ?start=0', paper='2014', topics='integration', subtopics='volumes_of_revolution'))
        db.session.add(Question(marks=6, question_id='2014Q9', question_number='9', video='KMs1zBdPMWA?start=0', paper='2014', topics='maclaurin_series'))
        db.session.add(Question(marks=6, question_id='2014Q8', question_number='8', video='AgGbOHdkjLc?start=0', paper='2014', topics='differential_equations'))
        db.session.add(Question(marks=4, question_id='2014Q7', question_number='7', video='OatWIT4Jvmw?start=0', paper='2014', topics='methods_of_proof,matrices', subtopics='induction'))
        db.session.add(Question(marks=3, question_id='2014Q6', question_number='6', video='LK7062rew8c?start=0', paper='2014', topics='differentiation', subtopics='chain_rule,product_rule,logarithmic'))
        db.session.add(Question(marks=4, question_id='2014Q5', question_number='5', video='EFUUcKl-7To?start=0', paper='2014', topics='vectors'))
        db.session.add(Question(marks=3, question_id='2014Q4', question_number='4', video='gVSByrvZahU?start=0', paper='2014', topics='differentiation', subtopics='chain_rule,parametric'))
        db.session.add(Question(marks=6, question_id='2014Q3', question_number='3', video='c0RZR4HpFqU?start=0', paper='2014', topics='systems_of_equations', subtopics='gaussian_elimination,inconsistency_redundancy'))
        db.session.add(Question(marks=5, question_id='2014Q2', question_number='2', video='rO4MaX5aef8?start=0', paper='2014', topics='binomial_theorem', subtopics='general_term'))
        db.session.add(Question(marks=6, question_id='2014Q1', question_number='1', video='l9Zyif2wG_A?start=0', paper='2014', topics='differentiation', subtopics='chain_rule,quotient_rule'))

        db.session.add(Question(marks=11, question_id='2015Q18', question_number='18', video='s8T6FTEIeho?start=0', paper='2015', topics='differential_equations'))
        db.session.add(Question(marks=9, question_id='2015Q17', question_number='17', video='tIHJi2lsEiA?start=0', paper='2015', topics='partial_fractions,integration', subtopics='irreducible_quadratic_factor,improper_rational_fraction,integration_partial_fractions'))
        db.session.add(Question(marks=10, question_id='2015Q16', question_number='16', video='0VtrvH4HDDA?start=0', paper='2015', topics='differential_equations'))
        db.session.add(Question(marks=10, question_id='2015Q15', question_number='15', video='t4O_RjPS38I?start=0', paper='2015', topics='vectors'))
        db.session.add(Question(marks=4, question_id='2015Q14', question_number='14', video='kTLIybXvx7k?start=0', paper='2015', topics='functions_graphs'))
        db.session.add(Question(marks=7, question_id='2015Q13', question_number='13', video='NUYxPjTXsOk?start=0', paper='2015', topics='complex_numbers'))
        db.session.add(Question(marks=3, question_id='2015Q12', question_number='12', video='JcvLlSAu9pI?start=0', paper='2015', topics='methods_of_proof', subtopics='direct'))
        db.session.add(Question(marks=4, question_id='2015Q11', question_number='11', video='sWUlbgcN7oo?start=0', paper='2015', topics='matrices'))
        db.session.add(Question(marks=5, question_id='2015Q10', question_number='10', video='OcVzHZP9UGg?start=0', paper='2015', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=4, question_id='2015Q9', question_number='9', video='S8mb-3PuNJk?start=0', paper='2015', topics='binomial_theorem'))
        db.session.add(Question(marks=3, question_id='2015Q8', question_number='8', video='NlWKcEd4P5c?start=0', paper='2015', topics='differentiation', subtopics='parametric,chain_rule'))
        db.session.add(Question(marks=4, question_id='2015Q7', question_number='7', video='Kkd_E16CkX0?start=0', paper='2015', topics='number_theory', subtopics='euclidean_algorithm'))
        db.session.add(Question(marks=3, question_id='2015Q6', question_number='6', video='QZmHeZ4hT8s?start=0', paper='2015', topics='differentiation', subtopics='logarithmic'))
        db.session.add(Question(marks=4, question_id='2015Q5', question_number='5', video='90KCR81zbng?start=0', paper='2015', topics='matrices'))
        db.session.add(Question(marks=4, question_id='2015Q4', question_number='4', video='30gC41P56WU?start=0', paper='2015', topics='differentiation', subtopics='implicit,chain_rule'))
        db.session.add(Question(marks=5, question_id='2015Q3', question_number='3', video='ImEMdaICL_g?start=0', paper='2015', topics='sequences_series'))
        db.session.add(Question(marks=6, question_id='2015Q2', question_number='2', video='0cLaW4QeCtI?start=0', paper='2015', topics='differentiation', subtopics='quotient_rule,product_rule,chain_rule'))
        db.session.add(Question(marks=4, question_id='2015Q1', question_number='1', video='000fn4tUUic?start=0', paper='2015', topics='binomial_theorem', subtopics='binomial_expansion'))

        db.session.add(Question(marks=9, question_id='2016Q16', question_number='16', video='Ppde6TnSYq4?start=0', paper='2016', topics='differential_equations'))
        db.session.add(Question(marks=10, question_id='2016Q15', question_number='15', video='FAQA_EF9qNM?start=0', paper='2016', topics='differential_equations'))
        db.session.add(Question(marks=9, question_id='2016Q14', question_number='14', video='JdgZcBvQr7s?start=0', paper='2016', topics='vectors'))
        db.session.add(Question(marks=9, question_id='2016Q13', question_number='13', video='gh4IwBDXeho?start=0', paper='2016', topics='integration,partial_fractions', subtopics='distinct_linear_factors,integration_partial_fractions'))
        db.session.add(Question(marks=4, question_id='2016Q12', question_number='12', video='cMT14r1OXDg?start=0', paper='2016', topics='functions_graphs'))
        db.session.add(Question(marks=4, question_id='2016Q11', question_number='11', video='Xe2ubLm4eLw?start=0', paper='2016', topics='differentiation', subtopics='related_rates'))
        db.session.add(Question(marks=4, question_id='2016Q10', question_number='10', video='Hxv_jdQ9d-4?start=0', paper='2016', topics='methods_of_proof', subtopics='direct,counter_example'))
        db.session.add(Question(marks=6, question_id='2016Q9', question_number='9', video='H1G2Uj25KjM?start=0', paper='2016', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=6, question_id='2016Q8', question_number='8', video='uYrM-65I5yI?start=0', paper='2016', topics='complex_numbers'))
        db.session.add(Question(marks=6, question_id='2016Q7', question_number='7', video='HHaL3AtSWRQ?start=0', paper='2016', topics='matrices'))
        db.session.add(Question(marks=6, question_id='2016Q6', question_number='6', video='vbR3u9gq7_w?start=0', paper='2016', topics='maclaurin_series'))
        db.session.add(Question(marks=4, question_id='2016Q5', question_number='5', video='mTFcNjUUZqE?start=0', paper='2016', topics='methods_of_proof', subtopics='induction'))
        db.session.add(Question(marks=4, question_id='2016Q4', question_number='4', video='yWRrdGVpIis?start=0', paper='2016', topics='systems_of_equations'))
        db.session.add(Question(marks=5, question_id='2016Q3', question_number='3', video='WuB0ism4OwQ?start=0', paper='2016', topics='binomial_theorem', subtopics='general_term'))
        db.session.add(Question(marks=6, question_id='2016Q2', question_number='2', video='TTA83H08vog?start=0', paper='2016', topics='sequences_series', subtopics='gaussian_elimination,inconsistency_redundancy'))
        db.session.add(Question(marks=2, question_id='2016Q1c', question_number='1c', video='av88Cfg1IhQ?start=245', paper='2016', topics='differentiation', subtopics='parametric'))
        db.session.add(Question(marks=3, question_id='2016Q1b', question_number='1b', video='av88Cfg1IhQ?start=105', paper='2016', topics='differentiation', subtopics='quotient_rule'))
        db.session.add(Question(marks=3, question_id='2016Q1a', question_number='1a', video='av88Cfg1IhQ?start=0', paper='2016', topics='differentiation', subtopics='chain_rule,product_rule'))

        db.session.add(Question(marks=7, question_id='2017Q18', question_number='18', video='9Ram5wv8O0I?start=0', paper='2017', topics='differentiation', subtopics='parametric,product_rule'))
        db.session.add(Question(marks=8, question_id='2017Q17', question_number='17', video='J01EefAXzTE?start=0', paper='2017', topics='complex_numbers'))
        db.session.add(Question(marks=5, question_id='2017Q16', question_number='16', video='y2JhRiT_cmU?start=0', paper='2017', topics='integration', subtopics='volumes_of_revolution'))
        db.session.add(Question(marks=9, question_id='2017Q15', question_number='15', video='ljtHMlHqxeo?start=0', paper='2017', topics='vectors'))
        db.session.add(Question(marks=10, question_id='2017Q14', question_number='14', video='FIWisVahXBU?start=0', paper='2017', topics='differential_equations'))
        db.session.add(Question(marks=4, question_id='2017Q13', question_number='13', video='r91bOckGSpA?start=0', paper='2017', topics='methods_of_proof', subtopics='contrapositive'))
        db.session.add(Question(marks=5, question_id='2017Q12', question_number='12', video='nsJZL7J29eE?start=0', paper='2017', topics='functions_graphs'))
        db.session.add(Question(marks=5, question_id='2017Q11', question_number='11', video='aQ2VZjtIySs?start=0', paper='2017', topics='differentiation', subtopics='product_rule,logarithmic'))
        db.session.add(Question(marks=4, question_id='2017Q10', question_number='10', video='AlNBZMcEHL4?start=0', paper='2017', topics='sequences_series'))
        db.session.add(Question(marks=5, question_id='2017Q9', question_number='9', video='jEBWU0nEl4I?start=0', paper='2017', topics='differential_equations'))
        db.session.add(Question(marks=4, question_id='2017Q8', question_number='8', video='zPS__BLPnMw?start=0', paper='2017', topics='number_theory', subtopics='euclidean_algorithm'))
        db.session.add(Question(marks=6, question_id='2017Q7', question_number='7', video='DyYaMNdacnE?start=0', paper='2017', topics='matrices'))
        db.session.add(Question(marks=6, question_id='2017Q6', question_number='6', video='y9Dbjnb9yzY?start=0', paper='2017', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=6, question_id='2017Q5', question_number='5', video='dt_Qgl39_R4?start=0', paper='2017', topics='systems_of_equations', subtopics='gaussian_elimination,inconsistency_redundancy'))
        db.session.add(Question(marks=5, question_id='2017Q4', question_number='4', video='eiKamTKptvE?start=0', paper='2017', topics='sequences_series'))
        db.session.add(Question(marks=3, question_id='2017Q3', question_number='3', video='-ViD0FyCoZo?start=0', paper='2017', topics='differentiation', subtopics='chain_rule,quotient_rule'))
        db.session.add(Question(marks=4, question_id='2017Q2', question_number='2', video='JyHb6-vnXA0?start=0', paper='2017', topics='partial_fractions', subtopics='repeated_linear_factor'))
        db.session.add(Question(marks=4, question_id='2017Q1', question_number='1', video='lKGtaEd5KN4?start=0', paper='2017', topics='binomial_theorem', subtopics='binomial_expansion'))

        db.session.add(Question(marks=10, question_id='2018Q17', question_number='17', video='7N5nZHzfpKo?start=0', paper='2018', topics='maclaurin_series'))
        db.session.add(Question(marks=10, question_id='2018Q16', question_number='16', video='g_O26EfxGak?start=0', paper='2018', topics='systems_of_equations,vectors', subtopics='gaussian_elimination,inconsistency_redundancy'))
        db.session.add(Question(marks=7, question_id='2018Q15b', question_number='15b', video='pY4yQzEvmmM?start=124', paper='2018', topics='differential_equations'))
        db.session.add(Question(marks=3, question_id='2018Q15a', question_number='15a', video='pY4yQzEvmmM?start=0', paper='2018', topics='integration', subtopics='parts'))
        db.session.add(Question(marks=10, question_id='2018Q14', question_number='14', video='XrRN-IXbIck?start=0', paper='2018', topics='sequences_series'))
        db.session.add(Question(marks=6, question_id='2018Q13', question_number='13', video='YxSEoZy9qdA?start=0', paper='2018', topics='differentiation', subtopics='related_rates'))
        db.session.add(Question(marks=5, question_id='2018Q12', question_number='12', video='bkvYdv_IsZU?start=0', paper='2018', topics='methods_of_proof', subtopics='induction'))
        db.session.add(Question(marks=5, question_id='2018Q11', question_number='11', video='feSCubuuULs?start=0', paper='2018', topics='matrices'))
        db.session.add(Question(marks=3, question_id='2018Q10', question_number='10', video='Ncbg3M7X8os?start=0', paper='2018', topics='complex_numbers'))
        db.session.add(Question(marks=3, question_id='2018Q9', question_number='9', video='rw1cFpou7qU?start=0', paper='2018', topics='methods_of_proof', subtopics='direct'))
        db.session.add(Question(marks=4, question_id='2018Q8', question_number='8', video='yzmV526Jd0c?start=0', paper='2018', topics='integration', subtopics='substitution'))
        db.session.add(Question(marks=5, question_id='2018Q7', question_number='7', video='rgtzntNhcVc?start=0', paper='2018', topics='matrices'))
        db.session.add(Question(marks=5, question_id='2018Q6', question_number='6', video='MNHM8tKNz2s?start=0', paper='2018', topics='differentiation', subtopics='parametric'))
        db.session.add(Question(marks=4, question_id='2018Q5', question_number='5', video='YWLI1aeQDsQ?start=0', paper='2018', topics='number_theory', subtopics='euclidean_algorithm'))
        db.session.add(Question(marks=3, question_id='2018Q4', question_number='4', video='3v2fdRMfQog?start=0', paper='2018', topics='complex_numbers'))
        db.session.add(Question(marks=5, question_id='2018Q3', question_number='3', video='UbP3DSqc-qU?start=0', paper='2018', topics='binomial_theorem', subtopics='general_term'))
        db.session.add(Question(marks=4, question_id='2018Q2', question_number='2', video='3ZIm0JLGnNg?start=0', paper='2018', topics='partial_fractions', subtopics='distinct_linear_factors'))
        db.session.add(Question(marks=4, question_id='2018Q1c', question_number='1c', video='ghqOOum12s0?start=168', paper='2018', topics='differentiation', subtopics='implicit,chain_rule,product_rule'))
        db.session.add(Question(marks=2, question_id='2018Q1b', question_number='1b', video='ghqOOum12s0?start=65', paper='2018', topics='differentiation', subtopics='chain_rule,quotient_rule'))
        db.session.add(Question(marks=2, question_id='2018Q1a', question_number='1a', video='ghqOOum12s0?start=0', paper='2018', topics='differentiation', subtopics='chain_rule'))

        db.session.commit()


setup_db(db, app)
